version: '3.8'

services:
  backend:
    build:
      context: ./anki_builder
    container_name: backend
    volumes:
      - ./anki_builder:/app
    depends_on:
      - db

  frontend:
    build:
      context: ./autonomous-anki-builder-frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: